#:import hex_color kivy.utils.get_color_from_hex

#:set WHITE_CHOCOLATE hex_color("#ECE5DD")
#:set TEA_GREEN hex_color("#DCF8C6")
#:set GREEN hex_color("#25D366")
#:set TEAL_GREEN hex_color("#128C7E")
#:set BANGLADESH_GREEN hex_color("#075e54")
#:set PICTON_BLUE hex_color("34B7F1")
#:set GRAY_CHATEAU hex_color("#9ca1a7")
#:set IRON hex_color("#d7d8da")
#:set ROLLING_STONE hex_color("#6c777d")
#:set EBONY_CLAY hex_color("#232d36")
#:set AZTEC hex_color("#101d25")